openapi: 3.0.1
info:
  title: API Lions de Genève Newsletter
  version: 1.0.0
  description: API interne simulée pour générer des newsletters des Lions de Genève.
servers:
  - url: https://gzouui.github.io/lions-geneve-plugin
paths:
  /news:
    get:
      summary: Dernières actualités
      responses:
        '200':
          description: Liste des actualités
          content:
            application/json:
              schema:
                type: object
                properties:
                  news:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        date:
                          type: string
  # ... le reste de ta spec
